server:
  port: 8080

spring:
  application:
    name: api-gateway

  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

        - id: connection-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

jwt:
  secretKey: YOUR_SECRET_HERE

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    reactor.netty: DEBUG

  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){cyan} %clr(%logger{36}){yellow} - %m%n"
