server:
  port: 8080

spring:
  application:
    name: api-gateway

  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      routes:

        # Normal username/password authentication
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        # Google OAuth - authorization
        - id: google-oauth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/oauth2/**

        # Google OAuth - callback
        - id: google-oauth-callback
          uri: lb://USER-SERVICE
          predicates:
            - Path=/login/oauth2/**

        # User APIs
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        # Posts APIs
        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=3
            - AuthenticationFilter

        # Connection APIs
        - id: connection-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - AuthenticationFilter

jwt:
  secretKey: qwertyuiopqwertyuiuopolkjhgfdsarthgvrehgbeuythgvbthgyebitugbtgbiugbivuhbngiuhgbuhbgibg

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    reactor.netty: DEBUG

  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){cyan} %clr(%logger{36}){yellow} - %m%n"
