spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - vEthernet.*
        - docker.*
        - VMware.*
        - VirtualBox.*

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
