server:
  port: 9030

spring:
  application:
    name: connection-service

  servlet:
    context-path: /connections

  neo4j:
    uri: neo4j://127.0.0.1:7687
    authentication:
      username: neo4j
      password: 12345678

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
